### ISSUE TITLE
Example may need updating

### ISSUE THREAD

**Issue by jmzagorski** [Swimlane/gulp-aspnet5#4]
i was going over your README and notice you were passing in "weblistener" as the task argument to start the server. I could not get this to work until I reviewed your source and saw I could pass in "run" for "dotnet run" Not sure if there was a change from RC2 to RTM 1.0 since I was only ever on RC1.

```
var server;
gulp.task("start:api", function (cb) {
  if (!server) server = new plug.dotnet({ cwd: "./" });
  server.start("run", cb);
});
```

**Comment by amcdnl** [comment]
Web listenerer was passed for a bug that was in krestel in rc1, it has since been fixed nd we are using krestel now.
